### ISSUE TITLE
Ability to see wether a cell is a sea, land or coast cell.

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MACS-docs#110]
Right now, unless you can test it by trying to build a road/platform/bridge or order a unit to move to a specific cell, which is not always possible, you can't know which type a cell is.

Comments on Discord : 

Slobjok : 

On many maps it's hard to know if a field is coast or not. In critical situations this leads to either bad moves with unpleasant surprises or you end up trying in a custom game. Both is not good. Any ideas how to improve this?

Malakia :

After many times coming into the position of needing to know whether it's a sea, land or coast cell...
I suggest adding that info to the road/platform/bridge or single cell building info panel OR if it's a cell without anything, tap it twice to see that info.

**Comment by Slobjok** [comment]
This would be a simple implementation. Good enough? I would think so.
https://user-images.githubusercontent.com/59515306/209118804-7eb34be9-6030-4ddb-a464-7d5ae9b516d2.mp4

**Comment by KatekovAnton** [comment]
Should be fixed in 18.1.0
