### ISSUE TITLE
Current resource distribution is not balanced. Especially with low gold and low resource density settings.

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MACS-docs#111]
If we want to start having competitions, this needs to be adressed. Too many games are decided by sheer luck, due to lots or lack of gold or little raw to start with, etc.

A few proposals have been made to solve this, like this one by Index : 
https://macsgame.com/resources/

**Comment by KatekovAnton** [comment]
fixed in v18.0.0
