### ISSUE TITLE
Confirmation dialog for "Upgrade All"

### ISSUE THREAD

**Issue by Slobjok** [KatekovAnton/MACS-docs#123]
When upgrades for a building type are available, the action menu contains entries "Upgrade" and "Upgrade All". The upgrade all entry can get very expensive and an uninteded click is bad.
As doing this is a rare action and an uninteded click somehow destroys your turn, a confirmation dialog would be good.
"Upgrade All [Building Type] for [amoung] ress?" "Yes" "No"

**Comment by KatekovAnton** [comment]
should be fixed in v18.0.0
