### ISSUE TITLE
First uniset is hidden by default

### ISSUE THREAD

**Issue by iindex** [KatekovAnton/MACS-docs#131]
Creating new game and heaving several unisets in the list, which cannot fit in one window, make the first one by default hidden. It is not intuitive when by default you need to scroll up to see the items, which does not fit.
The list should show items from the first one.
view by default:
![0-02-05-97c62f49deca915695625784efff7f7cc35a6ec2683a4b7abd98a4d36be4efe5_bca9962a28396518](https://user-images.githubusercontent.com/5329435/195055316-2ef71807-f14f-4962-9b00-f3200266719e.jpg)
Scrolling up:

![0-02-05-42e3f1b51fc1432496352c401fd18e429ef26fadd443a6c6c116a77c2174f5ca_2a998620661bfb69](https://user-images.githubusercontent.com/5329435/195055433-9dc81dd5-bc5a-4101-98e1-e6ab9617bbbc.jpg)

**Comment by KatekovAnton** [comment]
should be fixed in v18.0.0
