### ISSUE TITLE
Connector cost 1

### ISSUE THREAD

**Issue by iindex** [KatekovAnton/MACS-docs#132]
When connector cost is 1 raw material.
In "laying" mode engineer still consumes 2 raw material per connector.
In usual building mode. When engineer received an order to build connector it shows "Turns remain - 0" in the popup message on the same turn. On the next turn it shows same message and engineer is not ending building process and did not consume any raw material. Engineer cannot end building process at all.

**Comment by Hruks** [comment]
Laying cost is not reproduced: Connector laying required 1 mat for one item.  
Usual construction fixed.
Fixed: https://gitlab.com/void0main/maxtouch-external/-/merge_requests/71
