### ISSUE TITLE
Statistic window does not fit to the screen on android

### ISSUE THREAD

**Issue by iindex** [KatekovAnton/MACS-docs#133]
Statistic window does not fit to the screen on android
![0-02-05-4e9aadfa9b9e8f848f099932324e5233e29ce21a1f5ef3c39db2b3ac7da38c20_65c92999a57fb33f](https://user-images.githubusercontent.com/5329435/195539341-268bccd3-f6a8-4c95-8dfa-14da405300e2.jpg)

**Comment by KatekovAnton** [comment]
should be fixed in v18.0.0
