### ISSUE TITLE
Menu restricts unit selection 

### ISSUE THREAD

**Issue by DevilCCCP** [KatekovAnton/MACS-docs#134]
Menu appiars righter (vcenter) of unit. In most right cells it appiars over unit, restricts selection of units under selected i.g. landed unit under carriar.
Common case is right top/bottom, but may be right vcenter and left vcenter when can't be placed correctly to the right.
![Macs 01](https://user-images.githubusercontent.com/40351559/197379239-3192132e-aadc-4f4e-a619-8b6810238f72.png)

**Comment by DevilCCCP** [comment]
ver 17.0.4

**Comment by KatekovAnton** [comment]
uh

**Comment by KatekovAnton** [comment]
@DevilCCCP you should be able to select MOVE item - menu will disappear and you will be able to click any cell around

**Comment by DevilCCCP** [comment]
I need not to move, but to select unit under current (air transport).
It's possible only if 'zoom in' to cell size become more than menu size.
