### ISSUE TITLE
Submarine fires throw ground

### ISSUE THREAD

**Issue by DevilCCCP** [KatekovAnton/MACS-docs#135]
Torpedos moves throw ground. Most funny that it fires to the ground part of building placed partionaly on ground and water platforms.
![Macs bug 02](https://user-images.githubusercontent.com/40351559/197403777-b0774b2a-0320-4c2d-91c3-f9d94067f1dc.png)

**Comment by DevilCCCP** [comment]
ver 17.0.4

**Comment by KatekovAnton** [comment]
This issue is accepted...
