### ISSUE TITLE
[Recon] Ghost unit visible in final replay

### ISSUE THREAD

**Issue by iindex** [KatekovAnton/MACS-docs#136]
Game: 1vs1 (SW - NE) max 10 cells from corner
Turn: 27
Version: 18.0.0 beta 5
ghost units appear as on image below in final replay. Ghost appears when scout is out of scan range from Malakia
![image](https://user-images.githubusercontent.com/5329435/197500613-ea31d089-2a6e-4869-9764-d2f566e7331c.png)

**Comment by KatekovAnton** [comment]
should be fixed in v18.1.0
