### ISSUE TITLE
Save statistic issue

### ISSUE THREAD

**Issue by iindex** [KatekovAnton/MACS-docs#137]
Game: 1vs1 (SW - NE) max 10 cells from corner
![image](https://user-images.githubusercontent.com/5329435/197501053-d5856690-31e3-4e61-b26a-9bd61c55602e.png)
Spent raw is much more than extracted, which should not be the case.

**Comment by KatekovAnton** [comment]
Should be better now (from v18.0.0 b8)

**Comment by iindex** [comment]
Re-open the issue, it is still in place:
https://macsgame.com/gamestat/stat/623.html
![image](https://user-images.githubusercontent.com/5329435/221135081-806359b7-e2b1-4559-ac19-84cad12db0f8.png)

**Comment by KatekovAnton** [comment]
@iindex can you please investigate what is happening? what is really causing it?

**Comment by KatekovAnton** [comment]
Found and fixed one problem. Should be better in v19.0.0
