### ISSUE TITLE
Move and shot mechanics modification

### ISSUE THREAD

**Issue by iindex** [KatekovAnton/MACS-docs#145]
Now in uniset we have _pMoveAndShot parameter, which is 0/1 (true/false). We need to replace it with a percentage (0-100)
0 - unit loses shots when moving like it is now with Assault gun and gunboat
100 - unit does NOT lose shots when moving, like it is now with scout and bomber
20 - unit can move 20% of his speed and will NOT lose the shot ability. For example speed 10, 2 shots. The unit can move 2 cells, and still, have the ability to shoot 2 times. Then it will lose shots as usual - 8/2 = 4. The unit can move further 4 cells and will be able to shoot 1 time. And if that unit heaving full speed shots 2 time it should still be able to move 2 cells.

Possible to use the same uniset _pMoveAndShot parameter, which perhaps can be treated as real type: 0, 1, 0.2 to have backward compatibility.

**Comment by iindex** [comment]
It is working like that now. But I think it will be too much for missile units to move at full speed and shoot. Therefore I want to give them the ability to move 20-30% of their speed and shoot, for them to be move useful.

**Comment by KatekovAnton** [comment]
https://gitlab.com/void0main/maxtouch-external/-/merge_requests/100

will merge in v19 hopefully
