### ISSUE TITLE
add search by name feature in all units window

### ISSUE THREAD

**Issue by iindex** [KatekovAnton/MACS-docs#147]
Add search by name feature in all units window.
![image](https://github.com/KatekovAnton/MACS-docs/assets/5329435/3769a1e0-e481-4d85-b794-77984dcb2b6a)

Could be an additional button at the top near "ALL" with magnifying glass, which will ask for text and then displays a list.
Or just a text input underneath all buttons (all tabs), when a user enters text the content of the tabs should be filtered.

Now it is hard to find a certain type of unit. For example, you need to understand if you have at all surveyors.

**Comment by Slobjok** [comment]
https://github.com/KatekovAnton/MACS-docs/assets/59515306/4970b3b5-e137-4ab1-8f14-ac956ead8afc
Pushed to feature/issue147_search_unit_list_by_name, now creating merge request.

**Comment by KatekovAnton** [comment]
Done in 18.1.0
