### ISSUE TITLE
Clearly mark which unit is moving, for units that have pending movement at the end of the turn.

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MACS-docs#152]
When you press end turn and there is still pending movement of unit(s), the movement is then automatically executed, but many times it's unclear which unit it is. The camera moves to the area where the unit is, but the unit is not highlighted in any way.
Suggestion: add the white circle around the unit that is doing pending actions for a few seconds.

**Comment by KatekovAnton** [comment]
Game will select the unit

Fixed in v19
