### ISSUE TITLE
Infiltrator bug

### ISSUE THREAD

**Issue by cugi1** [KatekovAnton/MACS-docs#154]
During AI turn the game crashes or is going to stuck when AI infiltrator is discovered near large amount of gunturrets and shooting is about to start. Tested on 18.1.0 beta 4.
[Save-fire-bug.zip](https://github.com/KatekovAnton/MACS-docs/files/12359123/Save-fire-bug.zip)

**Comment by KatekovAnton** [comment]
Will be fixed in v19.0.0
