### ISSUE TITLE
Upgrade unit bug

### ISSUE THREAD

**Issue by cugi1** [KatekovAnton/MACS-docs#155]
Units placed in hangar/depot/barracks by addInitialUnitsForPlayer() and then storeUnitToCargo() cannot be upgraded.

**Comment by KatekovAnton** [comment]
do you mean they cant be upgraded from the script or manually in the game?

**Comment by KatekovAnton** [comment]
Found an issue, will be fixed in v19

Temporarily you can apply a workaround - make sure that unit in the depot has a physical location right next to the depot.
