### ISSUE TITLE
3 bugs in one save

### ISSUE THREAD

**Issue by cugi1** [KatekovAnton/MACS-docs#160]
Version 18.1.0 beta 4

Bug 1:  After "End turn" AI stops play, game frozen
Bug 2: AI produces only constructors in 10 HF and uses these for attack - produced only 75 constructors
Bug 3. AI changed produscion set by scenario author which makes the scenario corrupted.

Proper production set should be :

```
local playerPlants2 = {
  {91, 97, "hvplant", "crawler", 2},
	{94, 97, "hvplant", "crawler", 2},
	{97, 97, "hvplant", "rocket", 2},
	{100, 97, "hvplant", "rocket", 2},
	{102, 97, "hvplant", "asgun", 2},
	{105, 97, "hvplant", "asgun", 2},
	{91, 99, "hvplant", "scanner", 2},
	{102, 99, "hvplant", "tank", 2},
  {91, 92, "hvplant", "tank", 2},
	{100, 92, "hvplant", "tank", 2},
  {105, 92, "lightplant", "scout", 2},
	{105, 89, "lightplant", "scout", 2},
	{105, 86, "lightplant", "scout", 2},
	
	{94, 101, "hvplant", "tank", 1}, -- to have enough materials
	{96, 101, "hvplant", "tank", 1}, -- to have enough materials
}
```
[1692459738 3bugsonesave.zip](https://github.com/KatekovAnton/MACS-docs/files/12386673/1692459738.3bugsonesave.zip)

**Comment by KatekovAnton** [comment]
hi. please provide both .save as well as well as allsaves.json

**Comment by cugi1** [comment]
Here is allsaves.json
[allSaves.json](https://github.com/KatekovAnton/MACS-docs/files/13056047/allSaves.json)

**Comment by KatekovAnton** [comment]
Fixed, more or less
