### ISSUE TITLE
Finished building bug

### ISSUE THREAD

**Issue by cugi1** [KatekovAnton/MACS-docs#161]
When the building is finished, and constructor/builder leave build place, and is being killed immediately on square near the building, the building disappears.

**Comment by Malakia1** [comment]
I vote for this being a bug, it does not make sense to a player that a finished building is destroyed together with the constructor, on a other cell.

**Comment by KatekovAnton** [comment]
https://i.gyazo.com/420dc4989055a344d3a22ec6e00d42d4.mp4

Implemented in v19
