### ISSUE TITLE
Possible movement highlighter for enemy units

### ISSUE THREAD

**Issue by iindex** [KatekovAnton/MACS-docs#162]
When you select an enemy (or ally) unit the game will highlight its possible movement with consideration of remaining speed. This should be changed to highlight possible movement to always show full unit speed as when there is a turn of the enemy all his units will get full movement.

**Comment by Hruks** [comment]
https://gitlab.com/void0main/maxtouch-external/-/merge_requests/97

**Comment by KatekovAnton** [comment]
will merge in v19
