### ISSUE TITLE
Units language localization display issue

### ISSUE THREAD

**Issue by iindex** [KatekovAnton/MACS-docs#164]
In MACs uniset only 'en' localization is defined within uniset file. If in the application we select Russian language - the interface will be translated to Russian. However, units descriptions and names will still be in English. If uniset does not contain required by the user localization - then it should be used from the localization file.

![0-02-05-716e578ea8a193fb187a67db1e72753eb6c68c086c153e611addc4837f98b5c7_493859392e61c567](https://github.com/KatekovAnton/MACS-docs/assets/5329435/1b3394b9-1c2b-4508-ad1e-4bc78210c131)
![0-02-05-098fd2284bf8c0d1e2ee6fd2760d0c240a1fac4cac8951e0c9dda2f047d32c8d_dcec18eb526867b3](https://github.com/KatekovAnton/MACS-docs/assets/5329435/d20e67d0-3bb3-4847-ad69-435d53d83e53)
![0-02-05-f149b4487f8c99662d86369e72000f5225a7732dea116d5bfeb113726fb759a1_688bbc4df24b02eb](https://github.com/KatekovAnton/MACS-docs/assets/5329435/d96ae637-9ae9-4ca8-bb11-1ae413b8cdbe)
![0-02-05-3c06f5c30a076c03965d28762b1e94b40a359e002da88e7b8732bccef6147221_502e01ee0e3d7a37](https://github.com/KatekovAnton/MACS-docs/assets/5329435/3cbe1f3c-9572-4f6b-a748-c8b67d984f74)
![0-02-05-a26f91b4bd5ceeb5b1dedb6dbcf58cf8bad4d59e31e79102291d50f19c44964b_16b95fc90a8e56fd](https://github.com/KatekovAnton/MACS-docs/assets/5329435/c6d274a9-0622-4fd9-9f91-809981a4efda)

**Comment by KatekovAnton** [comment]
It depends on the screen. Please tell me what screen has the issue

**Comment by iindex** [comment]
It is everywhere. Added screenshots. Ukrainian localization is selected, Even though Ukrainian localization contains translation it takes the English texts from the Uniset file.

**Comment by KatekovAnton** [comment]
Fixed in v19.0.2
