### ISSUE TITLE
Additional game options screen

### ISSUE THREAD

**Issue by iindex** [KatekovAnton/MACS-docs#171]
More about options button should open option page, but opens uniset page. The back button is not visible
![0-02-05-0e7695c2db9b1329417d67a10ed9385382e2924d0772cd3af0632d14a05822cc_904e85326b958c1d](https://github.com/KatekovAnton/MACS-docs/assets/5329435/0abdae6d-7ec3-4f80-a2a7-913d8aedbc11)

**Comment by KatekovAnton** [comment]
Fixed in v19 0 0 beta 5

**Comment by KatekovAnton** [comment]
Oh just give me the correct link please lol

**Comment by iindex** [comment]
https://macsgame.com/h-game-options.html

**Comment by KatekovAnton** [comment]
Fixed in 19 0 0 beta 8
