### ISSUE TITLE
Factory automatic building speed swith

### ISSUE THREAD

**Issue by iindex** [KatekovAnton/MACS-docs#173]
When the factory is building for example, a constructor with cost 7, for example first turn it was 4x, then 2x and last third turn should be 1x. Factory should automatically change its building speed at the last turn, it correctly does that for raw mat consumption and building speed, however, energy consumption remains on the same level
![factory](https://github.com/KatekovAnton/MACS-docs/assets/5329435/573a270a-bbc3-425a-acd6-ccf4fe47d428)

**Comment by KatekovAnton** [comment]
Fixed in v19 0 0 beta 5
