### ISSUE TITLE
Localization label fall back

### ISSUE THREAD

**Issue by iindex** [KatekovAnton/MACS-docs#175]
if no translation is provided for a specific label (like s.msetts.textago) selected by the user language then it should fall back and display English text.

![0-02-05-ebe1c6063821ec88f9a98eec3031d2dfcb36b18babbe5ba857dcae01429fa42f_403d86bf01d16cf3](https://github.com/KatekovAnton/MACS-docs/assets/5329435/dbdcbee6-3d9c-4d0e-b884-84399199f9cb)

**Comment by Slobjok** [comment]
I worked on it, fixed in https://gitlab.com/void0main/maxtouch-external/-/merge_requests/144
