### ISSUE TITLE
Ability to prioritize gaining fuel surplus in energy management. 

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MACS-docs#183]
When having no fuel surplus, it must be possible to use energy surplus in the batteries instead of fuel, so a fuel surplus can be forced so units can be refueled instead of being dedicated to power stations currently

**Comment by KatekovAnton** [comment]
Closing as it is duplicated by the https://github.com/KatekovAnton/MACS-docs/issues/179
