### ISSUE TITLE
Battery/Energy consumption sometimes incorrect (when factories finish their job?)

### ISSUE THREAD

**Issue by KatekovAnton** [KatekovAnton/MACS-docs#184]
[Original message](https://discord.com/channels/411014559613059092/1271209357849264228/1271209357849264228) 

Slobjok:
Confirmed intermittently in local game 19.1.0 with MacsE Uniset, after I realised bad behaviour in multiplayer game in 19.1.0:
Have a base with some factories and a battery that has some energy stored.
Set your factories so that they use more energy than is produced. So that the stored energy needs to be used as well. End turn.
Expectation: the battery loses some energy.
Actual (bug): sometimes the battery does not lose energy. Speculation: I suspect that it has to do with factories finishing their job in that turn and that then their need is not correctly subtracted. But maybe that is a false assumption. I am currently not sure, what a stable repro is. I can only say that I experience it in my multiplayer game and had it once when I tested in local game.

Anyone else can confirm this or find a stable repro?

**Comment by Malakia1** [comment]
I think I had this in a game of mine.
Anton had a look at it and fixed it, he said it would only be available in new games (19.1.0 games).
Was your game started in a pre 19.1.0 version?

**Comment by KatekovAnton** [comment]
Should have been fixed by dc6071962fa7bf9ad98b6fb8374fc7b80d7741e5 

game should be started in 19.1.0

**Comment by KatekovAnton** [comment]
was fixed in august dc6071962fa7bf9ad98b6fb8374fc7b80d7741e5 so it will be fixed in 19.1.1

please try in latest betas
