### ISSUE TITLE
Rocket Launcher attack issue

### ISSUE THREAD

**Issue by iindex** [KatekovAnton/MACS-docs#189]
It seems like the attack of the Rocket Launcher on the main target is doubled. And the attack on constructing engineers is 4x.
Rocket Launcher with attack 20
Mobile AA 30 Hits 6 armor.  Main target. Mobile AA survived with 2 hits. 20-6 = 14 * 2 = 28
Engineer 16 hits 6 armor - secondary target. Destroyed. If the damage on the nearby cell is half of the main target, then it should be 10. 10 - 6 = 4 hits should be the damage, however, Engineer was destroyed.. 

https://github.com/user-attachments/assets/bcc2dac4-7b12-4956-941a-c4fd9dfd3daa

**Comment by KatekovAnton** [comment]
Will be fixed in 19.1.1
