### ISSUE TITLE
[Suggestion] Jump to idling building

### ISSUE THREAD

**Issue by ChadovDE** [KatekovAnton/MACS-docs#28]
Hi. I would like to have the possibility to jump to the next building of my base that is idling/out of power. In big bases I can check if all buildings operate, but its hard to find the idling buildings.

**Comment by Hruks** [comment]
We need customized units lists with filters and sort toolbuttons for get idle buildings, units with action points, ready constructors, units ready to fire and more like this.

**Comment by KatekovAnton** [comment]
we now have a special window for it
