### ISSUE TITLE
[Suggestion] Separate "Objectives" Tab for missions

### ISSUE THREAD

**Issue by marcu805** [KatekovAnton/MACS-docs#61]
For missions/scenarios, it would be also interesting to have a separate tab which will show the Objective. This, in order to facilitate the gameplay, when the player needs to summarize again the mission objectives.

**Comment by KatekovAnton** [comment]
@marcu805 can you link the design here? you can upload zip archive

**Comment by KatekovAnton** [comment]
lets close this because I stopped working on campaign
