### ISSUE TITLE
[Issue] Repairing constructors while they're building

### ISSUE THREAD

**Issue by rogual** [KatekovAnton/MACS-docs#64]
A repair unit can repair a constructor while it's building something, but only if you click on the square the constructor was in just before it started building.

I would expect to be able to repair the constructor by clicking any of the 4 squares of the construction site.

**Comment by Hruks** [comment]
Looks like expected behavior should be: repair unit can not interact with busy constructor.

**Comment by Hruks** [comment]
Final solution: Repair, Steal and Disable actions works on any cells of construction site
MR submitted: https://gitlab.com/void0main/maxtouch-external/-/merge_requests/134

**Comment by KatekovAnton** [comment]
Reviewing it

**Comment by KatekovAnton** [comment]
Will be released in v19.1.0
