### ISSUE TITLE
[Suggestion] Revert APC capacity back to 6.

### ISSUE THREAD

**Issue by earlyraven** [KatekovAnton/MACS-docs#94]
With movement coast on loading, it appears the reduction of APC capacity to 3 is no longer warranted as it attempts to address an issue that is no longer present.  Specifically, in the past, it seems people were afraid of infantry loaded APCs as they could load into APC, move APC up close, unload, shoot, load back in and retreat.  Movement cost on loading already addresses this concern, so I propose to restore APC capacity back to 6.

**Comment by iindex** [comment]
6 is too many even with implemented limitation. Should not be more that 4.
